    export const quotes = [
        "Talk is cheap. Show me the code. - Linus Torvalds",
        "Programs must be written for people to read, and only incidentally for machines to execute. - Harold Abelson",
        "First, solve the problem. Then, write the code. - John Johnson",
        "Any fool can write code that a computer can understand. Good programmers write code that humans can understand. - Martin Fowler",
        "Premature optimization is the root of all evil. - Donald Knuth",
        "Debugging is twice as hard as writing the code in the first place. - Brian Kernighan",
        "Simplicity is the soul of efficiency. - Austin Freeman",
        "Code is like humor. When you have to explain it, it's bad. - Cory House",
        "Fix the cause, not the symptom. - Steve Maguire",
        "Deleted code is debugged code. - Jeff Sickel",
        "Games are not about graphics, they're about mechanics. - Sid Meier",
        "A game is a series of interesting choices. - Sid Meier",
        "The player is the sun around which the entire design revolves. - Bruce Shelley",
        "Given the opportunity, players will optimize the fun out of a game. - Soren Johnson",
        "Good games are those that make players feel clever. - John Romero",
        "Design is not how it looks, design is how it works. - Steve Jobs",
        "Polish is what separates good games from great games. - Shigeru Miyamoto",
        "A delayed game is eventually good, but a rushed game is forever bad. - Shigeru Miyamoto",
        "If it's not fun, why bother? - Reggie Fils-Aimé",
        "Games give you a chance to excel, and if you're playing in good company you don't even mind if you lose. - Gary Gygax",
        "Walking on water and developing software from a specification are easy if both are frozen. - Edward V. Berard",
        "Before software can be reusable it first has to be usable. - Ralph Johnson",
        "The best error message is the one that never shows up. - Thomas Fuchs",
        "Testing leads to failure, and failure leads to understanding. - Burt Rutan",
        "Make it work, make it right, make it fast. - Kent Beck",
        "Software and cathedrals are much the same: first we build them, then we pray. - Sam Redwine",
        "Every great developer you know got there by solving problems they were unqualified to solve until they actually did it. - Patrick McKenzie",
        "Controlling complexity is the essence of computer programming. - Brian Kernighan",
        "Software is a great combination between artistry and engineering. - Bill Gates",
        "Measuring programming progress by lines of code is like measuring aircraft building progress by weight. - Bill Gates",
        "Players do not play games to see the game, they play to be the hero. - Nolan Bushnell",
        "Gameplay is king. - Hideo Kojima",
        "Games should be easy to learn and hard to master. - John Romero",
        "A good game teaches you how to play it. - Sid Meier",
        "Emotion is the key to immersion. - Hideo Kojima",
        "The fun comes from mastery, not from complexity. - Raph Koster",
        "If the player isn't smiling, you've failed. - Shigeru Miyamoto",
        "Surprise is the most powerful tool in a game designer's toolbox. - Jesse Schell",
        "Players remember emotions, not features. - Amy Hennig",
        "Games are the most elevated form of investigation. - Albert Einstein",
        "Optimism is an occupational hazard of programming. - Kent Beck",
        "Programs are meant to be read by humans and only incidentally by computers. - Donald Knuth",
        "The sooner you start to code, the longer the program will take. - Roy Carlson",
        "Software design is about making trade-offs. - Grady Booch",
        "Truth can only be found in one place: the code. - Robert C. Martin"
    ];
